### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by brownsarahm** [rhodyprog4ds/BrownFall20#10]
Hello @rhodyprog4ds/community 

We'll talk more about why your access to this has changed from that it being only open source to being a little more structured on Friday, but, if you'd like you can test out your new access privileges by clicking "assign yourself" to the right of this issue text.

**Comment by ruifangkuang** [comment]
I didn't see assign yourself to the right of this issue text

**Comment by mfaramarzi** [comment]
> 
> 
> I didn't see assign yourself to the right of this issue text

I guess that's because we have not accepted sth

**Comment by brownsarahm** [comment]
@mfaramarzi & @ruifangkuang it appears to be working now, try it again?

**Comment by mfaramarzi** [comment]
> @mfaramarzi & @ruifangkuang it appears to be working now, try it again?

@brownsarahm Not yet.

**Comment by ruifangkuang** [comment]
No

**Comment by mfaramarzi** [comment]
> @mfaramarzi & @ruifangkuang it appears to be working now, try it again?

Fixed. Thanks
