### ISSUE TITLE
Issue on page /portfolio/analyses.html

### ISSUE THREAD

**Issue by mfaramarzi** [rhodyprog4ds/BrownFall20#34]
@rhodyprog4ds/fall20instructors
Dear Professor Brown,

Would you please clarify about the cheetsheet? In this sentence _"Make a cheatsheet with examples of the several different parameter settings for common operations for one topic."_  what do the following terms refer to?

- parameter settings
- common operations
- topic

**Comment by brownsarahm** [comment]
This is an office hours question, Beibhinn has hours tomorrow.
